/* 권한설정이력 */
CREATE TRIGGER TR_C_COMTNEMPLYRSCRTYESTBSHIS
AFTER INSERT ON comtnemplyrscrtyestbs
EXECUTE 

INSERT INTO COMTNEMPLYRSCRTYESTBSHIS
(SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE, USE_AT,
FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, CRUD) 
VALUES 
(OBJ.SCRTY_DTRMN_TRGET_ID, OBJ.MBER_TY_CODE, OBJ.AUTHOR_CODE, OBJ.USE_AT,
SYSDATETIME, OBJ.FRST_REGISTER_ID, SYSDATETIME, OBJ.LAST_UPDUSR_ID, 'I')
;

CREATE TRIGGER TR_U_COMTNEMPLYRSCRTYESTBSHIS
AFTER UPDATE ON comtnemplyrscrtyestbs
EXECUTE 

INSERT INTO COMTNEMPLYRSCRTYESTBSHIS
(SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE, USE_AT, 
FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, CRUD) 
VALUES 
(OBJ.SCRTY_DTRMN_TRGET_ID, OBJ.MBER_TY_CODE, OBJ.AUTHOR_CODE, OBJ.USE_AT,
SYSDATETIME, OBJ.FRST_REGISTER_ID, SYSDATETIME, OBJ.LAST_UPDUSR_ID, 'U')
;

CREATE TRIGGER TR_D_COMTNEMPLYRSCRTYESTBSHIS
BEFORE DELETE ON comtnemplyrscrtyestbs
EXECUTE 

INSERT INTO COMTNEMPLYRSCRTYESTBSHIS
(SCRTY_DTRMN_TRGET_ID, MBER_TY_CODE, AUTHOR_CODE, CRUD, 
FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) 
VALUES 
(OBJ.SCRTY_DTRMN_TRGET_ID, OBJ.MBER_TY_CODE, OBJ.AUTHOR_CODE, 'D',
SYSDATETIME, OBJ.FRST_REGISTER_ID, SYSDATETIME, OBJ.LAST_UPDUSR_ID)
;

/* 권한별메뉴설정이력 */
CREATE TRIGGER TR_C_COMTNMENUCREATDTLSHIS
AFTER INSERT ON comtnmenucreatdtls
EXECUTE 

INSERT INTO COMTNMENUCREATDTLSHIS
(MENU_NO, AUTHOR_CODE, USE_AT,
FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, CRUD) 
VALUES 
(OBJ.MENU_NO, OBJ.AUTHOR_CODE, OBJ.USE_AT,
SYSDATETIME, OBJ.FRST_REGISTER_ID, SYSDATETIME, OBJ.LAST_UPDUSR_ID, 'I')
;

CREATE TRIGGER TR_U_COMTNMENUCREATDTLSHIS
AFTER UPDATE ON comtnmenucreatdtls
EXECUTE 

INSERT INTO COMTNMENUCREATDTLSHIS
(MENU_NO, AUTHOR_CODE, USE_AT,
FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, CRUD) 
VALUES 
(OBJ.MENU_NO, OBJ.AUTHOR_CODE, OBJ.USE_AT,
SYSDATETIME, OBJ.FRST_REGISTER_ID, SYSDATETIME, OBJ.LAST_UPDUSR_ID, 'U')
;